kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: go-app-route
  annotations:
    openshift.io/host.generated: 'true'
spec:
  path: /hello
  to:
    kind: Service
    name: go-app-service
    weight: 100
  port:
    targetPort: 8084
  tls:
    termination: edge
  wildcardPolicy: None
